export const ErrorCode = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_EMAIL: "INVALID_EMAIL",
  USER_IS_NOT_ADULT: "USER_MUST_BE_18_OR_OLDER",
  USER_PASSWORD_LENGTH: "PASSWORD_MUST_BE_6_CHARACTERS_OR_LONGER",
  INVALID_API_KEY: "INVALID_API_KEY",
  INVALID_PARAMS: "INVALID_PARAMS",
}
